### PR TITLE
Fix broken link to a package

### PR DESCRIPTION
**Pull request by ch3nkula**
Getting the `logrus` package has a broken link in the README file. This fixes it.

### CODE REVIEW

**Comment by mukete** [comment]
hasn't this fix  been merged yet ?

**Comment by ch3nkula** [comment]
@mukete, it hasn't been fixed yet.

**Comment by ch3nkula** [comment]
@Ch3ck, what's up with this PR? :)

**Comment by Ch3ck** [comment]
@ch3nkula @mukete I've been off the grid the past few weeks; hope it's good now. I'll continue working on this immediately. There's alot of pending stuff.

**Pull request merged**
